In [ ]:
import pandas as pd
import numpy as np

In [43]:
df=pd.read_excel(r"C:\Users\VARSHA\OneDrive\Documents\NASO\Impact_of_AI_on_Education_Responses.xlsx")

In [44]:
df.isnull().sum()

Timestamp                                                                                                                    0
  1.What best describes you?                                                                                                 0
  2. What is your level of education?                                                                                        0
3. Age Group                                                                                                                 0
4. Gender                                                                                                                    0
 5. Do you use AI tools for learning or teaching?                                                                            0
6. Which AI tools do you use most frequently? (Select all that apply)                                                        0
  7. How often do you use AI in your studies or teaching?                                                                    0
  8. Has AI improved your learning or teaching experience?                                                                   0
  9. Approximately how much time does AI save you each week for studying, preparing lessons, or completing assignments?      0
  10. AI helps me understand difficult concepts more effectively.                                                            0
  11. Which educational benefit of AI do you value the most?                                                                 0
  12. Do you believe AI helps improve employability by supporting skill development?                                         0
  13. Do you think excessive use of AI reduces students' critical thinking and creativity?                                   0
14.  Are you concerned that students may misuse AI for assignments or examinations?                                          0
15.  How concerned are you about privacy and data security while using AI-based educational platforms?                       0
 16. Do you think teachers and students require training to use AI effectively and responsibly?                              0
17. Overall, how do you rate AI's impact on education in India?                                                              0
dtype: int64

In [45]:
df.duplicated().sum()

np.int64(0)

In [46]:
df.head()

,Timestamp,1.What best describes you?,2. What is your level of education?,3. Age Group,4. Gender,5. Do you use AI tools for learning or teaching?,6. Which AI tools do you use most frequently? (Select all that apply),7. How often do you use AI in your studies or teaching?,8. Has AI improved your learning or teaching experience?,"9. Approximately how much time does AI save you each week for studying, preparing lessons, or completing assignments?",10. AI helps me understand difficult concepts more effectively.,11. Which educational benefit of AI do you value the most?,12. Do you believe AI helps improve employability by supporting skill development?,13. Do you think excessive use of AI reduces students' critical thinking and creativity?,14. Are you concerned that students may misuse AI for assignments or examinations?,15. How concerned are you about privacy and data security while using AI-based educational platforms?,16. Do you think teachers and students require training to use AI effectively and responsibly?,"17. Overall, how do you rate AI's impact on education in India?"
0,2026-06-17 13:01:33.555,Working Professional pursuing education,Undergraduate,21–30 years,Male,Yes,"ChatGPT, Google Gemini, Microsoft Copilot",Daily,Significantly,Less than 1 hour,Strongly Agree,Personalized Learning,Yes,Strongly Agree,Highly Concerned,Very Concerned,Yes,Very Positive
1,2026-06-17 13:04:36.361,Working,Postgraduate,21–30 years,Male,Yes,"ChatGPT, Google Gemini",Weekly,Significantly,1–3 hours,Strongly Agree,Better Research Assistance,Yes,Agree,Highly Concerned,Not Concerned,Not Sure,Neutral
2,2026-06-17 13:07:02.827,College Student,Postgraduate,21–30 years,Male,Yes,ChatGPT,Rarely,Moderately,Less than 1 hour,Neutral,Faster Assignment Completion,Not Sure,Neutral,Moderately Concerned,Neutral,Yes,Positive
3,2026-06-17 13:12:58.707,College Student,Postgraduate,21–30 years,Female,Yes,"ChatGPT, Google Gemini",Daily,Significantly,Less than 1 hour,Strongly Agree,Personalized Learning,Yes,Agree,Highly Concerned,Concerned,Yes,Positive
4,2026-06-17 13:14:43.424,College Student,Postgraduate,21–30 years,Male,Yes,"ChatGPT, Google Gemini, Microsoft Copilot",Daily,Significantly,1–3 hours,Agree,Skill Development,Yes,Agree,Highly Concerned,Concerned,Yes,Positive

In [47]:
df.head()

,Timestamp,1.What best describes you?,2. What is your level of education?,3. Age Group,4. Gender,5. Do you use AI tools for learning or teaching?,6. Which AI tools do you use most frequently? (Select all that apply),7. How often do you use AI in your studies or teaching?,8. Has AI improved your learning or teaching experience?,"9. Approximately how much time does AI save you each week for studying, preparing lessons, or completing assignments?",10. AI helps me understand difficult concepts more effectively.,11. Which educational benefit of AI do you value the most?,12. Do you believe AI helps improve employability by supporting skill development?,13. Do you think excessive use of AI reduces students' critical thinking and creativity?,14. Are you concerned that students may misuse AI for assignments or examinations?,15. How concerned are you about privacy and data security while using AI-based educational platforms?,16. Do you think teachers and students require training to use AI effectively and responsibly?,"17. Overall, how do you rate AI's impact on education in India?"
0,2026-06-17 13:01:33.555,Working Professional pursuing education,Undergraduate,21–30 years,Male,Yes,"ChatGPT, Google Gemini, Microsoft Copilot",Daily,Significantly,Less than 1 hour,Strongly Agree,Personalized Learning,Yes,Strongly Agree,Highly Concerned,Very Concerned,Yes,Very Positive
1,2026-06-17 13:04:36.361,Working,Postgraduate,21–30 years,Male,Yes,"ChatGPT, Google Gemini",Weekly,Significantly,1–3 hours,Strongly Agree,Better Research Assistance,Yes,Agree,Highly Concerned,Not Concerned,Not Sure,Neutral
2,2026-06-17 13:07:02.827,College Student,Postgraduate,21–30 years,Male,Yes,ChatGPT,Rarely,Moderately,Less than 1 hour,Neutral,Faster Assignment Completion,Not Sure,Neutral,Moderately Concerned,Neutral,Yes,Positive
3,2026-06-17 13:12:58.707,College Student,Postgraduate,21–30 years,Female,Yes,"ChatGPT, Google Gemini",Daily,Significantly,Less than 1 hour,Strongly Agree,Personalized Learning,Yes,Agree,Highly Concerned,Concerned,Yes,Positive
4,2026-06-17 13:14:43.424,College Student,Postgraduate,21–30 years,Male,Yes,"ChatGPT, Google Gemini, Microsoft Copilot",Daily,Significantly,1–3 hours,Agree,Skill Development,Yes,Agree,Highly Concerned,Concerned,Yes,Positive

In [48]:
print(df.columns)

Index(['Timestamp', '  1.What best describes you?  ',
       '  2. What is your level of education?  ', '3. Age Group', '4. Gender',
       ' 5. Do you use AI tools for learning or teaching?  ',
       '6. Which AI tools do you use most frequently? (Select all that apply)',
       '  7. How often do you use AI in your studies or teaching?  ',
       '  8. Has AI improved your learning or teaching experience?  ',
       '  9. Approximately how much time does AI save you each week for studying, preparing lessons, or completing assignments?  ',
       '  10. AI helps me understand difficult concepts more effectively.  ',
       '  11. Which educational benefit of AI do you value the most?  ',
       '  12. Do you believe AI helps improve employability by supporting skill development?  ',
       '  13. Do you think excessive use of AI reduces students' critical thinking and creativity?  ',
       '14.  Are you concerned that students may misuse AI for assignments or examinations? ',
       '15.  How concerned are you about privacy and data security while using AI-based educational platforms? ',
       ' 16. Do you think teachers and students require training to use AI effectively and responsibly?  ',
       '17. Overall, how do you rate AI's impact on education in India?  '],
      dtype='object')

In [49]:
df.to_csv("Education.csv", index=False)

In [50]:


df = df.rename(columns={
    "9. Approximately how much time does AI save you each week for studying, preparing lessons, or completing assignments?": "9. AI_Time_Saved"
})

In [42]:
# Remove the Timestamp column
df = df.drop(columns=["Timestamp"])

# Rename all remaining columns with short names
df.columns = [
    "Description",
    "Education_Level",
    "Age_Group",
    "Gender",
    "Uses_AI_for_Learning",
    "AI_Tools_Used",
    "AI_Usage_Frequency",
    "AI_Improved_Experience",
    "AI_Time_Saved",
    "AI_Concept_Understanding",
    "AI_Educational_Benefit",
    "AI_Employability_Impact",
    "AI_Critical_Thinking_Impact",
    "AI_Misuse_Concern",
    "Privacy_Security_Concern",
    "AI_Training_Needed",
    "Overall_AI_Impact"
]

KeyError: "['Timestamp'] not found in axis"

In [ ]:
print(df.columns)

Index(['Description', 'Education_Level', 'Age_Group', 'Gender',
       'Uses_AI_for_Learning', 'AI_Tools_Used', 'AI_Usage_Frequency',
       'AI_Improved_Experience', 'AI_Time_Saved', 'AI_Concept_Understanding',
       'AI_Educational_Benefit', 'AI_Employability_Impact',
       'AI_Critical_Thinking_Impact', 'AI_Misuse_Concern',
       'Privacy_Security_Concern', 'AI_Training_Needed', 'Overall_AI_Impact'],
      dtype='object')

Index(['Timestamp', '1.What best describes you?',
       '2. What is your level of education?', '3. Age Group', '4. Gender',
       '6. AI_Tools_Used',
       '7. How often do you use AI in your studies or teaching?',
       '8. Has AI improved your learning or teaching experience?',
       '9. Approximately how much time does AI save you each week for studying, preparing lessons, or completing assignments?',
       '10. AI helps me understand difficult concepts more effectively.',
       '11. Which educational benefit of AI do you value the most?',
       '12. Do you believe AI helps improve employability by supporting skill development?',
       '13. Do you think excessive use of AI reduces students' critical thinking and creativity?',
       '14.  Are you concerned that students may misuse AI for assignments or examinations?',
       '15.  How concerned are you about privacy and data security while using AI-based educational platforms?',
       '16. Do you think teachers and students require training to use AI effectively and responsibly?',
       '17. Overall, how do you rate AI's impact on education in India?'],
      dtype='object')

In [41]:
df.to_csv("Education.csv", index=False)